name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DOCKER_LOGIN }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/aay98/monitoring
          docker-compose down
          git pull
          git reset --hard HEAD
          docker-compose up --build -d 